// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webui/server/play_service.proto

/*
Package server is a generated protocol buffer package.

It is generated from these files:
	webui/server/play_service.proto

It has these top-level messages:
	NewGameRequest
	MoveRequest
*/
package server

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import kitchensink_solitaire_model "github.com/dhendry/kitchen-sink/solitaire/model"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NewGameRequest struct {
}

func (m *NewGameRequest) Reset()                    { *m = NewGameRequest{} }
func (m *NewGameRequest) String() string            { return proto.CompactTextString(m) }
func (*NewGameRequest) ProtoMessage()               {}
func (*NewGameRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type MoveRequest struct {
	Str string                                    `protobuf:"bytes,1,opt,name=str" json:"str,omitempty"`
	Tmp *kitchensink_solitaire_model.GameState_Id `protobuf:"bytes,2,opt,name=tmp" json:"tmp,omitempty"`
}

func (m *MoveRequest) Reset()                    { *m = MoveRequest{} }
func (m *MoveRequest) String() string            { return proto.CompactTextString(m) }
func (*MoveRequest) ProtoMessage()               {}
func (*MoveRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MoveRequest) GetStr() string {
	if m != nil {
		return m.Str
	}
	return ""
}

func (m *MoveRequest) GetTmp() *kitchensink_solitaire_model.GameState_Id {
	if m != nil {
		return m.Tmp
	}
	return nil
}

func init() {
	proto.RegisterType((*NewGameRequest)(nil), "kitchensink.solitaire.webui.server.NewGameRequest")
	proto.RegisterType((*MoveRequest)(nil), "kitchensink.solitaire.webui.server.MoveRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for PlayService service

type PlayServiceClient interface {
	NewGame(ctx context.Context, in *NewGameRequest, opts ...grpc.CallOption) (*kitchensink_solitaire_model.GameState, error)
}

type playServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlayServiceClient(cc *grpc.ClientConn) PlayServiceClient {
	return &playServiceClient{cc}
}

func (c *playServiceClient) NewGame(ctx context.Context, in *NewGameRequest, opts ...grpc.CallOption) (*kitchensink_solitaire_model.GameState, error) {
	out := new(kitchensink_solitaire_model.GameState)
	err := grpc.Invoke(ctx, "/kitchensink.solitaire.webui.server.PlayService/NewGame", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for PlayService service

type PlayServiceServer interface {
	NewGame(context.Context, *NewGameRequest) (*kitchensink_solitaire_model.GameState, error)
}

func RegisterPlayServiceServer(s *grpc.Server, srv PlayServiceServer) {
	s.RegisterService(&_PlayService_serviceDesc, srv)
}

func _PlayService_NewGame_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewGameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlayServiceServer).NewGame(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/kitchensink.solitaire.webui.server.PlayService/NewGame",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlayServiceServer).NewGame(ctx, req.(*NewGameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlayService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "kitchensink.solitaire.webui.server.PlayService",
	HandlerType: (*PlayServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "NewGame",
			Handler:    _PlayService_NewGame_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "webui/server/play_service.proto",
}

func init() { proto.RegisterFile("webui/server/play_service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 287 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x91, 0x41, 0x4b, 0xc4, 0x30,
	0x10, 0x85, 0xe9, 0x2e, 0x28, 0xa6, 0x28, 0x4b, 0x44, 0x58, 0x8a, 0xe0, 0xd2, 0x83, 0xac, 0x07,
	0x13, 0xa8, 0x20, 0x82, 0x37, 0x2f, 0xe2, 0x41, 0x91, 0xee, 0x4d, 0x04, 0x49, 0xdb, 0xa1, 0x0d,
	0xdb, 0x26, 0x35, 0x99, 0xb6, 0xd4, 0xa3, 0x37, 0xcf, 0xfe, 0x34, 0xff, 0x82, 0x3f, 0x44, 0xda,
	0xae, 0xac, 0x82, 0xe0, 0xde, 0x26, 0x0c, 0xdf, 0x9b, 0xf7, 0x5e, 0xc8, 0x51, 0x03, 0x51, 0x25,
	0xb9, 0x05, 0x53, 0x83, 0xe1, 0x65, 0x2e, 0xda, 0xa7, 0x6e, 0x96, 0x31, 0xb0, 0xd2, 0x68, 0xd4,
	0xd4, 0x5f, 0x4a, 0x8c, 0x33, 0x50, 0x56, 0xaa, 0x25, 0xb3, 0x3a, 0x97, 0x28, 0xa4, 0x01, 0xd6,
	0x63, 0x6c, 0xc0, 0xbc, 0x83, 0x42, 0x27, 0x90, 0xf3, 0xf5, 0xb6, 0x47, 0xbd, 0xc3, 0x54, 0xeb,
	0x34, 0x07, 0x2e, 0x4a, 0xc9, 0x85, 0x52, 0x1a, 0x05, 0x4a, 0xad, 0xec, 0xb0, 0xf5, 0x27, 0x64,
	0xef, 0x0e, 0x9a, 0x6b, 0x51, 0x40, 0x08, 0xcf, 0x15, 0x58, 0xf4, 0x1f, 0x89, 0x7b, 0xab, 0xeb,
	0xef, 0x27, 0x9d, 0x90, 0xb1, 0x45, 0x33, 0x75, 0x66, 0xce, 0x7c, 0x27, 0xec, 0x46, 0x7a, 0x49,
	0xc6, 0x58, 0x94, 0xd3, 0xd1, 0xcc, 0x99, 0xbb, 0xc1, 0x09, 0xfb, 0xdb, 0x59, 0xef, 0x85, 0x75,
	0xba, 0x0b, 0x14, 0x08, 0xec, 0x26, 0x09, 0x3b, 0x2a, 0x78, 0x73, 0x88, 0x7b, 0x9f, 0x8b, 0x76,
	0x31, 0xc4, 0xa3, 0x2f, 0x64, 0x7b, 0x75, 0x9f, 0x06, 0xec, 0xff, 0x90, 0xec, 0xb7, 0x59, 0xef,
	0x78, 0xb3, 0xf3, 0xfe, 0xfe, 0xeb, 0xc7, 0xe7, 0xfb, 0x68, 0x97, 0xba, 0x7d, 0x0d, 0x75, 0xc0,
	0x15, 0x34, 0x57, 0x17, 0x0f, 0xe7, 0xa9, 0xc4, 0xac, 0x8a, 0x58, 0xac, 0x0b, 0x9e, 0x64, 0xa0,
	0x12, 0xd3, 0xf2, 0x95, 0xe0, 0x69, 0xa7, 0xb8, 0x2e, 0x93, 0xff, 0xfc, 0xa1, 0x68, 0xab, 0x2f,
	0xef, 0xec, 0x2b, 0x00, 0x00, 0xff, 0xff, 0x76, 0x6c, 0x2d, 0x18, 0xb8, 0x01, 0x00, 0x00,
}
