// Code generated by protoc-gen-go. DO NOT EDIT.
// source: model/solitaire.proto

/*
Package model is a generated protocol buffer package.

It is generated from these files:
	model/solitaire.proto

It has these top-level messages:
	Card
	Pile
	GameState
	Move
*/
package model

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Ordering here is based on the "bridge standard" which uses ascending alphabetical ordering.
// Not that it really matters...
// https://en.wikipedia.org/wiki/Suit_(cards)#Ranking_of_suits
type Suit int32

const (
	Suit_NO_SUIT  Suit = 0
	Suit_CLUBS    Suit = 1
	Suit_DIAMONDS Suit = 2
	Suit_HEARTS   Suit = 3
	Suit_SPADES   Suit = 4
)

var Suit_name = map[int32]string{
	0: "NO_SUIT",
	1: "CLUBS",
	2: "DIAMONDS",
	3: "HEARTS",
	4: "SPADES",
}
var Suit_value = map[string]int32{
	"NO_SUIT":  0,
	"CLUBS":    1,
	"DIAMONDS": 2,
	"HEARTS":   3,
	"SPADES":   4,
}

func (x Suit) String() string {
	return proto.EnumName(Suit_name, int32(x))
}
func (Suit) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type Rank int32

const (
	Rank_NO_RANK Rank = 0
	Rank_ACE     Rank = 1
	Rank_TWO     Rank = 2
	Rank_THREE   Rank = 3
	Rank_FOUR    Rank = 4
	Rank_FIVE    Rank = 5
	Rank_SIX     Rank = 6
	Rank_SEVEN   Rank = 7
	Rank_EIGHT   Rank = 8
	Rank_NINE    Rank = 9
	Rank_TEN     Rank = 10
	Rank_JACK    Rank = 11
	Rank_QUEEN   Rank = 12
	Rank_KING    Rank = 13
)

var Rank_name = map[int32]string{
	0:  "NO_RANK",
	1:  "ACE",
	2:  "TWO",
	3:  "THREE",
	4:  "FOUR",
	5:  "FIVE",
	6:  "SIX",
	7:  "SEVEN",
	8:  "EIGHT",
	9:  "NINE",
	10: "TEN",
	11: "JACK",
	12: "QUEEN",
	13: "KING",
}
var Rank_value = map[string]int32{
	"NO_RANK": 0,
	"ACE":     1,
	"TWO":     2,
	"THREE":   3,
	"FOUR":    4,
	"FIVE":    5,
	"SIX":     6,
	"SEVEN":   7,
	"EIGHT":   8,
	"NINE":    9,
	"TEN":     10,
	"JACK":    11,
	"QUEEN":   12,
	"KING":    13,
}

func (x Rank) String() string {
	return proto.EnumName(Rank_name, int32(x))
}
func (Rank) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type PileType int32

const (
	PileType_NO_PILE PileType = 0
	// The main deck
	// Cards are always face down in this pile
	PileType_DECK PileType = 1
	// Turn cards over from the deck to the waste pile to cycle through the deck.
	// If there are cards in this pile, at least the top card should be visible
	PileType_WASTE        PileType = 2
	PileType_TABLEAU_0    PileType = 10
	PileType_TABLEAU_1    PileType = 11
	PileType_TABLEAU_2    PileType = 12
	PileType_TABLEAU_3    PileType = 13
	PileType_TABLEAU_4    PileType = 14
	PileType_TABLEAU_5    PileType = 15
	PileType_TABLEAU_6    PileType = 16
	PileType_FOUNDATION_0 PileType = 20
	PileType_FOUNDATION_1 PileType = 21
	PileType_FOUNDATION_2 PileType = 22
	PileType_FOUNDATION_3 PileType = 23
)

var PileType_name = map[int32]string{
	0:  "NO_PILE",
	1:  "DECK",
	2:  "WASTE",
	10: "TABLEAU_0",
	11: "TABLEAU_1",
	12: "TABLEAU_2",
	13: "TABLEAU_3",
	14: "TABLEAU_4",
	15: "TABLEAU_5",
	16: "TABLEAU_6",
	20: "FOUNDATION_0",
	21: "FOUNDATION_1",
	22: "FOUNDATION_2",
	23: "FOUNDATION_3",
}
var PileType_value = map[string]int32{
	"NO_PILE":      0,
	"DECK":         1,
	"WASTE":        2,
	"TABLEAU_0":    10,
	"TABLEAU_1":    11,
	"TABLEAU_2":    12,
	"TABLEAU_3":    13,
	"TABLEAU_4":    14,
	"TABLEAU_5":    15,
	"TABLEAU_6":    16,
	"FOUNDATION_0": 20,
	"FOUNDATION_1": 21,
	"FOUNDATION_2": 22,
	"FOUNDATION_3": 23,
}

func (x PileType) String() string {
	return proto.EnumName(PileType_name, int32(x))
}
func (PileType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Card struct {
	Rank Rank `protobuf:"varint,1,opt,name=rank,enum=kitchensink.solitaire.model.Rank" json:"rank,omitempty"`
	Suit Suit `protobuf:"varint,2,opt,name=suit,enum=kitchensink.solitaire.model.Suit" json:"suit,omitempty"`
	// False means face down obviously
	FaceUp bool `protobuf:"varint,3,opt,name=face_up,json=faceUp" json:"face_up,omitempty"`
}

func (m *Card) Reset()                    { *m = Card{} }
func (m *Card) String() string            { return proto.CompactTextString(m) }
func (*Card) ProtoMessage()               {}
func (*Card) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Card) GetRank() Rank {
	if m != nil {
		return m.Rank
	}
	return Rank_NO_RANK
}

func (m *Card) GetSuit() Suit {
	if m != nil {
		return m.Suit
	}
	return Suit_NO_SUIT
}

func (m *Card) GetFaceUp() bool {
	if m != nil {
		return m.FaceUp
	}
	return false
}

type Pile struct {
	// NO_PILE is invalid
	PileType PileType `protobuf:"varint,1,opt,name=pile_type,json=pileType,enum=kitchensink.solitaire.model.PileType" json:"pile_type,omitempty"`
	// Cards are order from the bottom of the pile to the top of the pile.
	// The card at index 0 is at the bottom, and the card that is at index len()-1 is at the top (ie: typically playable).
	Cards []*Card `protobuf:"bytes,2,rep,name=cards" json:"cards,omitempty"`
}

func (m *Pile) Reset()                    { *m = Pile{} }
func (m *Pile) String() string            { return proto.CompactTextString(m) }
func (*Pile) ProtoMessage()               {}
func (*Pile) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Pile) GetPileType() PileType {
	if m != nil {
		return m.PileType
	}
	return PileType_NO_PILE
}

func (m *Pile) GetCards() []*Card {
	if m != nil {
		return m.Cards
	}
	return nil
}

type GameState struct {
	// Fixed for the duration of the game across all moves.
	GameId     *GameState_Id         `protobuf:"bytes,1,opt,name=game_id,json=gameId" json:"game_id,omitempty"`
	StateToken *GameState_StateToken `protobuf:"bytes,2,opt,name=state_token,json=stateToken" json:"state_token,omitempty"`
	// Only one pile of each type should be present. Piles SHOULD (but are not guaranteed) to be ordered by their
	// PileType tag.
	Piles []*Pile `protobuf:"bytes,10,rep,name=piles" json:"piles,omitempty"`
}

func (m *GameState) Reset()                    { *m = GameState{} }
func (m *GameState) String() string            { return proto.CompactTextString(m) }
func (*GameState) ProtoMessage()               {}
func (*GameState) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GameState) GetGameId() *GameState_Id {
	if m != nil {
		return m.GameId
	}
	return nil
}

func (m *GameState) GetStateToken() *GameState_StateToken {
	if m != nil {
		return m.StateToken
	}
	return nil
}

func (m *GameState) GetPiles() []*Pile {
	if m != nil {
		return m.Piles
	}
	return nil
}

// Game IDs must be globally unique and used only once
type GameState_Id struct {
	Seed int64 `protobuf:"fixed64,1,opt,name=seed" json:"seed,omitempty"`
	// Note that this nonce only technically needs to be unique within the context of the seed, but should
	// obviously by cryptographically securely generated
	Nonce int64 `protobuf:"fixed64,2,opt,name=nonce" json:"nonce,omitempty"`
}

func (m *GameState_Id) Reset()                    { *m = GameState_Id{} }
func (m *GameState_Id) String() string            { return proto.CompactTextString(m) }
func (*GameState_Id) ProtoMessage()               {}
func (*GameState_Id) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 0} }

func (m *GameState_Id) GetSeed() int64 {
	if m != nil {
		return m.Seed
	}
	return 0
}

func (m *GameState_Id) GetNonce() int64 {
	if m != nil {
		return m.Nonce
	}
	return 0
}

type GameState_StateToken struct {
	MoveNum int32 `protobuf:"varint,1,opt,name=move_num,json=moveNum" json:"move_num,omitempty"`
}

func (m *GameState_StateToken) Reset()                    { *m = GameState_StateToken{} }
func (m *GameState_StateToken) String() string            { return proto.CompactTextString(m) }
func (*GameState_StateToken) ProtoMessage()               {}
func (*GameState_StateToken) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2, 1} }

func (m *GameState_StateToken) GetMoveNum() int32 {
	if m != nil {
		return m.MoveNum
	}
	return 0
}

type Move struct {
	SrcPile  PileType `protobuf:"varint,1,opt,name=src_pile,json=srcPile,enum=kitchensink.solitaire.model.PileType" json:"src_pile,omitempty"`
	DestPile PileType `protobuf:"varint,2,opt,name=dest_pile,json=destPile,enum=kitchensink.solitaire.model.PileType" json:"dest_pile,omitempty"`
	// Number of cards counted from the "top" (largest index) to the bottom (least index) in the src deck
	NumCards int32 `protobuf:"varint,3,opt,name=num_cards,json=numCards" json:"num_cards,omitempty"`
}

func (m *Move) Reset()                    { *m = Move{} }
func (m *Move) String() string            { return proto.CompactTextString(m) }
func (*Move) ProtoMessage()               {}
func (*Move) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Move) GetSrcPile() PileType {
	if m != nil {
		return m.SrcPile
	}
	return PileType_NO_PILE
}

func (m *Move) GetDestPile() PileType {
	if m != nil {
		return m.DestPile
	}
	return PileType_NO_PILE
}

func (m *Move) GetNumCards() int32 {
	if m != nil {
		return m.NumCards
	}
	return 0
}

func init() {
	proto.RegisterType((*Card)(nil), "kitchensink.solitaire.model.Card")
	proto.RegisterType((*Pile)(nil), "kitchensink.solitaire.model.Pile")
	proto.RegisterType((*GameState)(nil), "kitchensink.solitaire.model.GameState")
	proto.RegisterType((*GameState_Id)(nil), "kitchensink.solitaire.model.GameState.Id")
	proto.RegisterType((*GameState_StateToken)(nil), "kitchensink.solitaire.model.GameState.StateToken")
	proto.RegisterType((*Move)(nil), "kitchensink.solitaire.model.Move")
	proto.RegisterEnum("kitchensink.solitaire.model.Suit", Suit_name, Suit_value)
	proto.RegisterEnum("kitchensink.solitaire.model.Rank", Rank_name, Rank_value)
	proto.RegisterEnum("kitchensink.solitaire.model.PileType", PileType_name, PileType_value)
}

func init() { proto.RegisterFile("model/solitaire.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 684 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0x5d, 0x4f, 0xdb, 0x48,
	0x14, 0xc5, 0x8e, 0x93, 0x38, 0x37, 0x81, 0xbd, 0x1a, 0xc1, 0x92, 0x85, 0x17, 0x36, 0xd2, 0x6a,
	0x59, 0xa4, 0x4d, 0x48, 0x58, 0xb6, 0xaf, 0x75, 0x92, 0x01, 0xdc, 0x80, 0x43, 0xc7, 0x0e, 0x54,
	0x7d, 0xb1, 0x4c, 0x3c, 0x05, 0x2b, 0xb1, 0x1d, 0xf9, 0x03, 0x89, 0xe7, 0x3e, 0xf7, 0xb1, 0x3f,
	0xa2, 0x3f, 0xa0, 0x3f, 0xa7, 0xff, 0xa5, 0x9a, 0x49, 0x80, 0x88, 0x07, 0x0a, 0x2f, 0xd1, 0x3d,
	0x37, 0xe7, 0x9c, 0x9c, 0x99, 0x7b, 0x33, 0xb0, 0x11, 0xc6, 0x3e, 0x9f, 0xb6, 0xd2, 0x78, 0x1a,
	0x64, 0x5e, 0x90, 0xf0, 0xe6, 0x2c, 0x89, 0xb3, 0x98, 0x6c, 0x4f, 0x82, 0x6c, 0x7c, 0xc3, 0xa3,
	0x34, 0x88, 0x26, 0xcd, 0xc7, 0x2f, 0x25, 0xb9, 0xf1, 0x45, 0x01, 0xad, 0xe7, 0x25, 0x3e, 0x39,
	0x04, 0x2d, 0xf1, 0xa2, 0x49, 0x5d, 0xd9, 0x51, 0x76, 0xd7, 0x3a, 0x7f, 0x36, 0x9f, 0x11, 0x35,
	0x99, 0x17, 0x4d, 0x98, 0xa4, 0x0b, 0x59, 0x9a, 0x07, 0x59, 0x5d, 0x7d, 0x81, 0xcc, 0xce, 0x83,
	0x8c, 0x49, 0x3a, 0xd9, 0x84, 0xf2, 0x27, 0x6f, 0xcc, 0xdd, 0x7c, 0x56, 0x2f, 0xec, 0x28, 0xbb,
	0x3a, 0x2b, 0x09, 0x38, 0x9a, 0x35, 0x3e, 0x2b, 0xa0, 0x9d, 0x07, 0x53, 0x4e, 0xba, 0x50, 0x99,
	0x05, 0x53, 0xee, 0x66, 0x77, 0x33, 0xbe, 0x08, 0xf5, 0xd7, 0xb3, 0xee, 0x42, 0xe5, 0xdc, 0xcd,
	0x38, 0xd3, 0x67, 0x8b, 0x8a, 0xbc, 0x81, 0xe2, 0xd8, 0x4b, 0xfc, 0xb4, 0xae, 0xee, 0x14, 0x76,
	0xab, 0xbf, 0x48, 0x27, 0x6e, 0x81, 0xcd, 0xf9, 0x8d, 0xef, 0x2a, 0x54, 0x8e, 0xbd, 0x90, 0xdb,
	0x99, 0x97, 0x89, 0x28, 0xe5, 0x6b, 0x2f, 0xe4, 0x6e, 0xe0, 0xcb, 0x20, 0xd5, 0xce, 0x3f, 0xcf,
	0x1a, 0x3d, 0x08, 0x9b, 0xa6, 0xcf, 0x4a, 0x42, 0x69, 0xfa, 0x84, 0x41, 0x35, 0x15, 0x3d, 0x37,
	0x8b, 0x27, 0x3c, 0x92, 0xd7, 0x55, 0xed, 0xb4, 0x5f, 0xe8, 0x23, 0x3f, 0x1d, 0x21, 0x64, 0x90,
	0x3e, 0xd4, 0xe2, 0x78, 0xe2, 0xa8, 0x69, 0x1d, 0x5e, 0x70, 0x3c, 0x71, 0x3d, 0x6c, 0xce, 0xdf,
	0x6a, 0x82, 0x6a, 0xfa, 0x84, 0x80, 0x96, 0x72, 0x3e, 0x3f, 0x13, 0x32, 0x59, 0x93, 0x75, 0x28,
	0x46, 0x71, 0x34, 0xe6, 0x32, 0x20, 0xb2, 0x39, 0xd8, 0xfa, 0x1b, 0xe0, 0x31, 0x02, 0xf9, 0x03,
	0xf4, 0x30, 0xbe, 0xe5, 0x6e, 0x94, 0x87, 0x52, 0x5b, 0x64, 0x65, 0x81, 0xad, 0x3c, 0x6c, 0x7c,
	0x53, 0x40, 0x3b, 0x8b, 0x6f, 0x39, 0x79, 0x0b, 0x7a, 0x9a, 0x8c, 0x5d, 0xf1, 0x73, 0xaf, 0x1b,
	0x5e, 0x39, 0x4d, 0xc6, 0xf7, 0xf3, 0xf7, 0x79, 0x9a, 0xcd, 0x2d, 0xd4, 0x57, 0xcd, 0x5f, 0xe8,
	0xa4, 0xc7, 0x36, 0x54, 0xa2, 0x3c, 0x74, 0xe7, 0x3b, 0x50, 0x90, 0x51, 0xf5, 0x28, 0x0f, 0xc5,
	0xa4, 0xd3, 0xbd, 0x3e, 0x68, 0x62, 0x21, 0x49, 0x15, 0xca, 0xd6, 0xd0, 0xb5, 0x47, 0xa6, 0x83,
	0x2b, 0xa4, 0x02, 0xc5, 0xde, 0xe9, 0xa8, 0x6b, 0xa3, 0x42, 0x6a, 0xa0, 0xf7, 0x4d, 0xe3, 0x6c,
	0x68, 0xf5, 0x6d, 0x54, 0x09, 0x40, 0xe9, 0x84, 0x1a, 0xcc, 0xb1, 0xb1, 0x20, 0x6a, 0xfb, 0xdc,
	0xe8, 0x53, 0x1b, 0xb5, 0xbd, 0xaf, 0x0a, 0x68, 0xe2, 0xef, 0xb0, 0xb0, 0x61, 0x86, 0x35, 0xc0,
	0x15, 0x52, 0x86, 0x82, 0xd1, 0xa3, 0xa8, 0x88, 0xc2, 0xb9, 0x1c, 0xa2, 0x2a, 0x8c, 0x9d, 0x13,
	0x46, 0x29, 0x16, 0x88, 0x0e, 0xda, 0xd1, 0x70, 0xc4, 0x50, 0x93, 0x95, 0x79, 0x41, 0xb1, 0x28,
	0x78, 0xb6, 0xf9, 0x01, 0x4b, 0x82, 0x67, 0xd3, 0x0b, 0x6a, 0x61, 0x59, 0x94, 0xd4, 0x3c, 0x3e,
	0x71, 0x50, 0x17, 0x44, 0xcb, 0xb4, 0x28, 0x56, 0xa4, 0x21, 0xb5, 0x10, 0x44, 0xeb, 0x9d, 0xd1,
	0x1b, 0x60, 0x55, 0xf0, 0xde, 0x8f, 0x28, 0xb5, 0xb0, 0x26, 0x9a, 0x03, 0xd3, 0x3a, 0xc6, 0xd5,
	0xbd, 0x1f, 0x0a, 0xe8, 0xf7, 0x37, 0xb2, 0xc8, 0x76, 0x6e, 0x9e, 0x52, 0x5c, 0x11, 0x9c, 0x3e,
	0xed, 0x0d, 0x50, 0x11, 0xc2, 0x4b, 0xc3, 0x76, 0x28, 0xaa, 0x64, 0x15, 0x2a, 0x8e, 0xd1, 0x3d,
	0xa5, 0xc6, 0xc8, 0xdd, 0x47, 0x58, 0x86, 0x6d, 0xac, 0x2e, 0xc3, 0x0e, 0xd6, 0x96, 0xe1, 0x01,
	0xae, 0x2e, 0xc3, 0xff, 0x70, 0x6d, 0x19, 0x1e, 0xe2, 0x6f, 0xcb, 0xf0, 0x7f, 0x44, 0x82, 0x50,
	0x3b, 0x1a, 0x8e, 0xac, 0xbe, 0xe1, 0x98, 0x43, 0xcb, 0xdd, 0xc7, 0xf5, 0x27, 0x9d, 0x36, 0x6e,
	0x3c, 0xe9, 0x74, 0xf0, 0xf7, 0x27, 0x9d, 0x03, 0xdc, 0xec, 0xb6, 0x3f, 0xb6, 0xae, 0x83, 0xec,
	0x26, 0xbf, 0x6a, 0x8e, 0xe3, 0xb0, 0xe5, 0xdf, 0xf0, 0xc8, 0x4f, 0xee, 0x5a, 0x8b, 0xfd, 0xf8,
	0x57, 0x2c, 0xc8, 0xe3, 0x3b, 0xd8, 0x92, 0x0b, 0x72, 0x55, 0x92, 0xcf, 0xe1, 0xc1, 0xcf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x6f, 0xc1, 0xc4, 0x54, 0x27, 0x05, 0x00, 0x00,
}
